name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy_docs:

    runs-on: ubuntu-latest

    steps:
    - name: Check-out
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Set up Pypi settings
      uses: bernardo-mg/deployment-pypi-settings-action@v1.0.4
      env:
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build distribution
      run: python setup.py sdist bdist_wheel
    - name: Deploy
      run: twine upload dist/*
